apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_session_token = FwoGZXIvYXdzEAQaDJMJWuJSyieU2VYCySLVAaHsbOjsjq7bbeEQQOCM1t6oA5NLAunU5RCKvdWp1M1LEBaDEzweaxNnlxQ01+VToU4q6vNaeJbKUmW25chAManJRQd7yTFmElDYYl2Kl7v3mjdm/A2/5y2pgezjluvoqn27noIkdz/8i3l0EOzqQ81c/08alq2CljFBoYzC66ieLq3IZOeAfHgbohx976YBGVAuqQEt6LLQuXVtiU2bItTwab3tF9ZWrSuY6rpBMieWDdN9AVCMRnXUlV6B0f6TYqZ64DsB+SLT5mzzlBw7idbajPb5jyiE4+yZBjIt9UBFIxmfKnYUvkB7G2t+G2fGEC++lo0+QiQVAOPFlFt2l5fjv8MLTDXX0h3W
    aws_access_key_id = ASIA5XUIA43UVQYYDVOI
    aws_secret_access_key = uvUZFFXp8SBg44Y93C4XDAkEH5gbsV1ePYWn/NzG

